DROP DATABASE IF EXISTS nrseq_test;
CREATE DATABASE nrseq_test;
USE nrseq_test;

CREATE TABLE tblDatabase (
   id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255),
   description VARCHAR(255)
);

CREATE TABLE tblProteinSequence (
   id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   sequence TEXT NOT NULL
);

CREATE TABLE tblProtein (
   id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   proteinID INT UNSIGNED NOT NULL,
   sequenceID INT UNSIGNED NOT NULL
);

CREATE TABLE tblProteinDatabase (
   id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   proteinID INT UNSIGNED NOT NULL,
   databaseID INT UNSIGNED NOT NULL,
   accessionString VARCHAR(255) NOT NULL,
   description VARCHAR(255),
   URL VARCHAR(255),
   timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   isCurrent ENUM('T','F')
);

