//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.01 at 02:54:01 PM PDT 
//

// @javax.xml.bind.annotation.XmlSchema(namespace = "http://psidev.info/psi/pi/mzIdentML/1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.yeastrc.ms.writer.mzidentml.jaxb;
