//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.02 at 02:00:15 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.unimod.org/xmlns/schema/unimod_2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.yeastrc.ms.parser.unimod.jaxb;
