/**
 * StringUtilsTest.java
 * @author Vagisha Sharma
 * Dec 3, 2010
 */
package edu.uwpr.protinfer.util;

import java.util.ArrayList;
import java.util.List;

import junit.framework.TestCase;

/**
 * 
 */
public class StringUtilsTest extends TestCase {

	public void testGetCoveredSequenceLength() {
		
		String protein = "WNLASSRVPFLFRVL*SA*R*SRHQKSSAVPMGRLRAVR*IVSVLCSSAKPSSPAACRRGSCRSLTATTPCPLFQPTS*KILLPGCLMENRVHTTPNCVLSPRKRKGLGHHLTLPLSKMALQKLS*RSPKRT*TGSLSLNLPFVVTVLLMCLSQKKLDKNQNTKQEGTGRGA*NMTPCWSRALSKQLLCLRSRVLQIKRFQLRKSLVQTLEETKTTC*NTMSVIWCGPKCRVTLGGLAWFLQIHSFTAIPNLKVRKRVHASITYSSLVTPQKELGYLRRAS*LLKEKDSLKNYARKVPSRHPRKLRKLSY*NLFQGN*GPSGKWALFKQKKLQACQWRSGKPSSPFYTWGTSFISTLK*PRRLALLQSLSEKWQSPQESVKKLLKTPSLREKRAFP*REGGGPNCVALQRPWRVTPM**RVLLKRRQRLTPEEE*RLLLGGRRPQPLRHEAGREMQHPSFWSSVKNTGMRWWLSTQMLQVRRLKSCSGHSGVC*VRSRERATTPSLPWWPLSRLKKTLVT*MGKKETTQRGHRTLQKMLRLRTHPGKDSGQTSTVFGXXXXXXXXXXEQALTRPWRQPPRSRARQQRKICLMHANH*RSEIGLPRQHLQLLGLAKVHLLLHP*LRMRSRTARETSPRSPHMKVQMKHKLKCLSHPKSLSEELLPKRSTCASCVRSQAASCSVKDPAAELSTSPALGFPGGQKGGSPAASVPQGFTHVSCVKRARQMLSAVW*LSVENFTMRLV*KNTL*LYLRAEVSAAPFTAV*AATLPTLQTQGHQKVK*CGVSAAPLPITAGMLVWQQDVQ*SPPTASSALPTSLLGRGSDTTPTST*AGALCAPKGGAFCAASPAQRPSTLTA*TSRCLMAAGSATTAGLGRSCTSRISFG*NLGTTDGGRQKFAIPKMFPQIFRK*STRLENSLCFSLGLKIITGRIRRECSRTWRGTGAAATRGSEGSEESSKTHCKKLKLVFVKLSFRGKPEKHRRASASPHHTSTSR*ISLTGKSRSTQRIFQKSLSATASPQMRILVALIRSV*TGC*CLSATRRCVPQASSARTSASPSASTQRPRSSRQMAKGGAWSPRGISERENLLTSTSGS*SMRRSAWRESSTHMRTTSPTSTCSL*TXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXPQRPFLQRKRAXXXXXXXXXXXXXXXXXXSQRTSASAAAMAGSWCCVTASSAPRPTTCPAWALASGPSGSGNVLGIIVTCVANLQLHFATSAPIHSVRSTRTGQPSAAPRTGRSYCCEHDLGAASVRSAKTEKPPPEPGKPKGKRRRRRGWRRVTEGK";
    	//protein = protein.replaceAll("\\*", "");
    	List<String> subseqList = new ArrayList<String>();
    	subseqList.add("VKCGVSAAPLPITAGMLVWQQ");
    	subseqList.add("CGVSAAPLPITAGMLVWQQDV");
    	
    	int covered = StringUtils.getCoveredSequenceLength(protein, subseqList);
    	assertEquals(covered, "VKCGVSAAPLPITAGMLVWQQDV".length());
	}
}
