package org.yeastrc.www.philiusws;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "PhiliusWSException", targetNamespace = "http://ws.philius.yeastrc.org/")
public class PhiliusWSException_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private PhiliusWSException faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public PhiliusWSException_Exception(String message,
			PhiliusWSException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 * @param cause
	 */
	public PhiliusWSException_Exception(String message,
			PhiliusWSException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: org.yeastrc.www.philiusws.PhiliusWSException
	 */
	public PhiliusWSException getFaultInfo() {
		return faultInfo;
	}

}
