package org.yeastrc.www.philiusws;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PhiliusPredictorDelegate", targetNamespace = "http://ws.philius.yeastrc.org/")
public interface PhiliusPredictorDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         javax.xml.ws.Response<org.yeastrc.www.philiusws.GetResultsResponse
	 *         >
	 */
	@WebMethod(operationName = "getResults")
	@RequestWrapper(localName = "getResults", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.GetResults")
	@ResponseWrapper(localName = "getResultsResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.GetResultsResponse")
	public Response<GetResultsResponse> getResultsAsync(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param asyncHandler
	 * @param arg0
	 * @return returns java.util.concurrent.Future<? extends java.lang.Object>
	 */
	@WebMethod(operationName = "getResults")
	@RequestWrapper(localName = "getResults", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.GetResults")
	@ResponseWrapper(localName = "getResultsResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.GetResultsResponse")
	public Future<?> getResultsAsync(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<GetResultsResponse> asyncHandler);

	/**
	 * 
	 * @param arg0
	 * @return returns org.yeastrc.www.philiusws.PhiliusSequenceAnnotationWS
	 * @throws PhiliusWSException_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getResults", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.GetResults")
	@ResponseWrapper(localName = "getResultsResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.GetResultsResponse")
	public PhiliusSequenceAnnotationWS getResults(
			@WebParam(name = "arg0", targetNamespace = "") int arg0)
			throws PhiliusWSException_Exception;

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         javax.xml.ws.Response<org.yeastrc.www.philiusws.SubmitSequenceResponse
	 *         >
	 */
	@WebMethod(operationName = "submitSequence")
	@RequestWrapper(localName = "submitSequence", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.SubmitSequence")
	@ResponseWrapper(localName = "submitSequenceResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.SubmitSequenceResponse")
	public Response<SubmitSequenceResponse> submitSequenceAsync(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param asyncHandler
	 * @param arg0
	 * @return returns java.util.concurrent.Future<? extends java.lang.Object>
	 */
	@WebMethod(operationName = "submitSequence")
	@RequestWrapper(localName = "submitSequence", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.SubmitSequence")
	@ResponseWrapper(localName = "submitSequenceResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.SubmitSequenceResponse")
	public Future<?> submitSequenceAsync(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<SubmitSequenceResponse> asyncHandler);

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 * @throws PhiliusWSException_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "submitSequence", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.SubmitSequence")
	@ResponseWrapper(localName = "submitSequenceResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.SubmitSequenceResponse")
	public int submitSequence(
			@WebParam(name = "arg0", targetNamespace = "") String arg0)
			throws PhiliusWSException_Exception;

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         javax.xml.ws.Response<org.yeastrc.www.philiusws.IsJobDoneResponse
	 *         >
	 */
	@WebMethod(operationName = "isJobDone")
	@RequestWrapper(localName = "isJobDone", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.IsJobDone")
	@ResponseWrapper(localName = "isJobDoneResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.IsJobDoneResponse")
	public Response<IsJobDoneResponse> isJobDoneAsync(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param asyncHandler
	 * @param arg0
	 * @return returns java.util.concurrent.Future<? extends java.lang.Object>
	 */
	@WebMethod(operationName = "isJobDone")
	@RequestWrapper(localName = "isJobDone", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.IsJobDone")
	@ResponseWrapper(localName = "isJobDoneResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.IsJobDoneResponse")
	public Future<?> isJobDoneAsync(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<IsJobDoneResponse> asyncHandler);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 * @throws PhiliusWSException_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "isJobDone", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.IsJobDone")
	@ResponseWrapper(localName = "isJobDoneResponse", targetNamespace = "http://ws.philius.yeastrc.org/", className = "org.yeastrc.www.philiusws.IsJobDoneResponse")
	public boolean isJobDone(
			@WebParam(name = "arg0", targetNamespace = "") int arg0)
			throws PhiliusWSException_Exception;

}
